import type { Metadata } from "next";
import Navegation from "@/ui/components/Navegation";
import "../styles/globals.css";


export const metadata: Metadata = {
  title: "Libro-Click",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <Navegation />
        {children}
      </body>
    </html>
  );
}
